### ISSUE TITLE
countByCountry should be sortable. 

### ISSUE THREAD

**Issue by simonv3** [TheTorProject/ooni-api#16]
either on the front-end or through the API.

@hellais @TylerJFisher

**Comment by TylerJFisher** [comment]
We should be able to perform sorting in the front-end - I'd like to avoid sorting in the API as much as possible in order to increase performance. IMO the API should be as lightweight, and flexible as possible - meaning that we can't guarantee that an order will be imposed on data in transit.

I'm blocked right now - but I'll try to get the data models set up as soon as I can (waiting for @hellais, @joelanders to reply to my e-mail with regards to local ooni-pipeline development).
