### ISSUE TITLE
Loader conflicts with ordering in the ui-grid

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-api#20]
When I click on the column headers in the ui-grid on the explorer tab I can only toggle ordering in one direction.

That is I click once, for example the test start time column, to order ASC, then if I click again it will still order ASC.

This is because the loading `$rootScope` variable makes the DOM for the ui-grid directive disappear and then reappear hence resetting all the state.

I think perhaps this should be overcome by making the loader not be something that hides what is bellow, but instead appears on top of all the elements.

**Comment by simonv3** [comment]
Hmm, so this is strange. When using `ng-if` the grid shows fine, but like you pointed out, there's a new scope every time, which breaks the sorting. Using `ng-show` would technically fix this because ng-show doesn't create a new scope, but then the grid doesn't load! 

For now I think the sorting is more important than the perfect transition between loading and not showing the grid, so I've just left it off with no ng-show. The grid shows, but it's empty, I think that's okay. The loading bar still shows.

**Comment by hellais** [comment]
This is now fixed.
